# Generated by Django 4.0.6 on 2022-07-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_footwear_shoemodel_shoecolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoecolor',
            name='model',
        ),
        migrations.RemoveField(
            model_name='shoemodel',
            name='brand',
        ),
        migrations.DeleteModel(
            name='FootWear',
        ),
        migrations.DeleteModel(
            name='ShoeColor',
        ),
        migrations.DeleteModel(
            name='ShoeModel',
        ),
    ]
